server:
  port: 8080
spring:
  datasource:
    # jdbc 连接基础配置
    username: root
    password: 666666
    #使用的 mysql 版本为：Server version: 5.6.11 MySQL Community Server (GPL)
    #mysql 驱动版本：mysql-connector-java-8.0.16.jar
    #高版本 Mysql 驱动时，配置的 driver-class-name 不再是 com.mysql.jdbc.Driver，url 后面必须设置时区 serverTimezone
    url: jdbc:mysql://127.0.0.1:3306/student_system?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# mybatis_plus 日志配置
mybatis_plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


    spring:
      jackson:
        time-zone=GMT+8:
          spring.jackson.date-format=yyyy-MM-dd HH:mm:ss:


